[general]
import = ["~/.config/alacritty/catppuccin-mocha.toml"]
[window]
decorations = "None"
opacity = 1

[scrolling]
multiplier = 5

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "ExtraBold" }
size = 20

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Block", blinking = "Always" }
blink_interval = 400

[terminal]
shell = "/bin/fish"

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
  { key = "Space", mods = "Control|Shift", action = "ToggleViMode" },
  { key = "q", mode = "Vi", action = "ToggleViMode" },
]
